# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

businesses = Business.create([{name: 'Thiel Group', shortdesc: 'Re-Engineered Systematic Protocol', longdesc: 'Enhance your team productivity with ultimate monitoring and cloud-based mixfield generation.', location: 'Bronx, NY', founded: '1981-12-12', founders: 'Nate Underhill, Sam Underhill'}, {name: 'Wunsch PLC', shortdesc: 'Business-Focused Background Opensystem', longdesc: 'Come join the most business facing team around as we turn your profits skyward and return your investors all their good capital.', location: 'Lewes, DE', founded: '1945-02-10', founders: 'Captain Marshall, William Dell'}, {name: 'Rolfson Group', shortdesc: 'Fully-Configurable Directional Open Architecture', longdesc: 'Here at Rolfson we take your old PHP scripts and infuse them with all the new UI glitz and glamor that will bring the customers flocking.', location: 'Boulder, CO', founded: '2017-01-01', founders: 'Teddy Rolfson, Angelica Singleterry'}, {name: 'Wolf PLC', shortdesc: 'Persevering Homogeneous Strategy', longdesc: 'Are you staying with the times? We can keep your customers happy by keeping what was considered "old" business strategy and showing you that "old is new" again.', location: 'Denver, CO', founded: '1989-07-27', founders: 'Curtis Davis, Belinda McAbee, Steven Churlowski'}, {name: 'Nam-zim', shortdesc: 'Single Entity Analysis and Postdesign', longdesc: 'We used to just do refrigerator repair and maintenance but when firdges went smart...so did we?!?!?! The number one IoT enterprise.', location: 'Juneau, AK', founded: '1998-08-08', founders: 'Harry Namson, Yuer Zim'}, {name: 'Onto Media', shortdesc: 'Production and PostProduction Experts', longdesc: 'We will make your next ad campaign sing with our revolutionized production process.', location: "Salt Lake City, UT", founded: '2012-10-22', founders:'Alicia Connel, Kyle Farmer, Diane Werner'}, {name: 'Yrjänä', shortdesc: 'Single Entity Processing Solutions', longdesc:'Specializing in mind-science-awareness programming for the future of application/physical interface development', location: 'Silicon Valley, CA', founded: '2019-03-09', founders: 'Uri Gurzmann, Amardeep Dhanju, Frank Skilerry'}, {name: 'Wardman & Herbers', shortdesc: 'Persevering Upward-Trending Concepts', longdesc:'Located in the heart of downtown booming Pittsburgh we aim to keep your business on track and experience the upward trend that we all desire', location: 'Pittsburgh, PA', founded: '2000-09-20', founders: 'Gene Wardman, Max Herbers'}])

