# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

businesses = Business.create([{name: 'Thiel Group', shortdesc: 'Re-Engineered Systematic Protocol', longdesc: 'Enhance your team productivity with ultimate monitoring and cloud-based mixfield generation.', location: 'Bronx, NY', founded: '1981-12-12'}, {name: 'Wunsch PLC', shortdesc: 'Business-Focused Background Opensystem', longdesc: 'Come join the most business facing team around as we turn your profits skyward and return your investors all their good capital.', location: 'Lewes, DE', founded: '1945-02-10'}, {name: 'Rolfson Group', shortdesc: 'Fully-Configurable Directional Open Architecture', longdesc: 'Here at Rolfson we take your old PHP scripts and infuse them with all the new UI glitz and glamor that will bring the customers flocking.', location: 'Boulder, CO', founded: '2017-01-01'}, {name: 'Wolf PLC', shortdesc: 'Persevering Homogeneous Strategy', longdesc: 'Are you staying with the times? We can keep your customers happy by keeping what was considered "old" business strategy and showing you that "old is new" again.', location: 'Denver, CO', founded: '1989-07-27'}, {name: 'Nam-zim', shortdesc: 'Single Entity Analysis and Postdesign', longdesc: 'We used to just do refrigerator repair and maintenance but when firdges went smart...so did we?!?!?! The number one IoT enterprise.', location: 'Juneau, AK', founded: '1998-08-08'}, {name: 'Onto Media', shortdesc: 'Production and PostProduction Experts', longdesc: 'We will make your next ad campaign sing with our revolutionized production process.', location: "Salt Lake City, UT", founded: '2012-10-22'}, {name: 'Yrjänä', shortdesc: 'Single Entity Processing Solutions', longdesc:'Specializing in mind-science-awareness programming for the future of application/physical interface development', location: 'Silicon Valley, CA', founded: '2019-03-09'}, {name: 'Wardman & Herbers', shortdesc: 'Persevering Upward-Trending Concepts', longdesc:'Located in the heart of downtown booming Pittsburgh we aim to keep your business on track and experience the upward trend that we all desire', location: 'Pittsburgh, PA', founded: '2000-09-20'}, {name: 'Yearavato', shortdesc: 'Styled Plugin Component Architecture', longdesc:'Serious styling for all of you mobile development needs.', location: 'San Francisco, CA', founded: '2017-09-20'}, {name: 'BuzzCorp', shortdesc: 'Uplifting Styled Paradigms', longdesc:'Bring positivity to your web application with this certified BCorp', location: 'Sandusky, OH', founded: '2004-09-20'}, {name: 'Scrim Fabricators LLC', shortdesc: 'Hardware Experts', longdesc:'Design and implement the latest in hardware fabrication technologies.', location: 'Atlanta, GA', founded: '2009-10-20'}, {name: 'Fritz, Camby, & Shingle', shortdesc: 'Guided Directional Logistics', longdesc:'All of you software development legal representation in one firm.', location: 'Philadelphia, PA', founded: '1983-06-30'}])


founders = Founder.create([{name: 'Nate Underhill', businessid: 1}, {name: 'Sam Underhill', businessid: 1}, {name: 'Captain Marshall', businessid: 2}, {name: 'William Dell', businessid: 2}, {name: 'Gene Wardman', businessid: 3}, {name:'Max Herbers', businessid: 3}, {name: 'Uri Gurzmann', businessid: 4}, {name: 'Amardeep Dhanju', businessid: 4}, {name:' Frank Skilerry', businessid: 5}, {name: 'Harry Namson', businessid:5},  {name: 'Yuer Zim', businessid: 6}, {name: 'Curtis Davis', businessid: 6}, {name: 'Belinda McAbee', businessid: 4}, {name: 'Steven Churlowski', businessid: 6}, {name: 'Reginald Butler', businessid: 10}, {name: 'Harry Cortland', businessid: 11}, {name: 'Gerard Pique', businessid: 11}, {name: 'Donna Hurley', businessid: 11}, {name: 'Carl Sagan', businessid: 12}, {name: 'Pat McReady', businessid: 12}, {name: 'Tenzin Gyatso', businessid: 7}, {name: 'Steph Gardner', businessid: 8}, {name: 'Quinn Sadler', businessid: 8}, {name: 'Robert Fischer', businessid: 9}, {name: 'Desmond Dekker', businessid: 10}])

